[project]
name = "data-sci-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Minh Le", email = "lehnminh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas",
]

[project.scripts]
data-sci-practice = "data_sci_practice:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
